import type { Building, Conflict, Discovery, Robot, SimEvent } from "./types";
export { buildings, streets } from "./city";

export const INCIDENT = {
  name: "Op Halcyon",
  place: "Halcyon Waterfront · Sector 4",
  magnitude: "6.8 Mw",
  startLabel: "05 Sep 2026 · 09:13 local",
  peopleMissing: 40,
  robotsDeployed: 6,
  mapKnownAtOpen: 0.39,
};

export const MISSION_START_SEC = 47 * 60;

export const initialRobots: Robot[] = [
  {
    id: "kite",
    callsign: "KITE-2",
    class: "uav",
    role: "rooftop mapping",
    x: 900,
    y: 250,
    heading: 28,
    battery: 64,
    lastHeardSec: MISSION_START_SEC - 3,
    radio: "strong",
    status: "mapping",
    payload: ["RGB", "lidar strip", "thermal"],
    can: ["map", "route-find", "overhead"],
    notes: "Flying a lawnmower over Harbor House. Best eyes we have. Cannot enter voids.",
  },
  {
    id: "mole",
    callsign: "MOLE-1",
    class: "crawler",
    role: "confined space",
    x: 448,
    y: 220,
    heading: 210,
    battery: 41,
    lastHeardSec: MISSION_START_SEC - 252,
    radio: "lost",
    status: "silent",
    payload: ["CO2", "cam", "mic"],
    can: ["void", "rubble"],
    notes: "Last packet from inside the parking pancake. Reported tapping, then nothing. May still be working. May be crushed. Treat as last-known.",
  },
  {
    id: "whisper",
    callsign: "WHISPER-4",
    class: "acoustic",
    role: "voice / knock listen",
    x: 700,
    y: 200,
    heading: 90,
    battery: 77,
    lastHeardSec: MISSION_START_SEC - 6,
    radio: "strong",
    status: "searching",
    payload: ["array mics", "knock"],
    can: ["listen", "localize"],
    notes: "Pinned on Harbor House A. Three voices, one small. Wants a snake or crawler to enter.",
  },
  {
    id: "bear",
    callsign: "BEAR-3",
    class: "heavy",
    role: "debris & corridor",
    x: 1240,
    y: 380,
    heading: 0,
    battery: 58,
    lastHeardSec: MISSION_START_SEC - 9,
    radio: "weak",
    status: "searching",
    payload: ["arm", "cam", "gas"],
    can: ["push", "hospital", "block"],
    notes: "On the hospital apron. Radio is thinning behind the wing. Path into the ward is contested.",
  },
  {
    id: "thread",
    callsign: "THREAD-5",
    class: "snake",
    role: "void entry",
    x: 680,
    y: 500,
    heading: 320,
    battery: 71,
    lastHeardSec: MISSION_START_SEC - 4,
    radio: "strong",
    status: "searching",
    payload: ["cam", "led", "temp"],
    can: ["void", "floor", "pipe"],
    notes: "Clear of the market. Fastest body we have for a third-floor void if a route exists.",
  },
  {
    id: "relay",
    callsign: "RELAY-6",
    class: "relay",
    role: "mesh mule",
    x: 520,
    y: 360,
    heading: 300,
    battery: 82,
    lastHeardSec: MISSION_START_SEC - 2,
    radio: "strong",
    status: "relaying",
    payload: ["mesh", "store-forward"],
    can: ["restore", "queue"],
    notes: "Holding line-of-sight toward MOLE. One block west and we may hear the crawler again.",
  },
];

export const initialDiscoveries: Discovery[] = [
  {
    id: "s14",
    kind: "survivor",
    x: 760,
    y: 190,
    title: "Three voices, Harbor House A",
    detail: "Two adults, one child, east face, roughly 3rd floor. Thermal matches. They answered a knock.",
    confidence: 0.82,
    lastUpdateSec: MISSION_START_SEC - 6,
    sourceRobot: "whisper",
    priority: 1,
    people: 3,
    access: "Balcony / inferred alley behind A. Not a void.",
    status: "new",
  },
  {
    id: "s09",
    kind: "survivor",
    x: 430,
    y: 230,
    title: "Tapping in the parking void",
    detail: "MOLE-1 heard rhythmic tapping under the pancake, then dropped. This is a life signal with a four-minute silence after it.",
    confidence: 0.54,
    lastUpdateSec: MISSION_START_SEC - 252,
    sourceRobot: "mole",
    priority: 1,
    people: 1,
    access: "Void under collapsed parking. Confined-space only.",
    status: "new",
    staleWarning: "The robot that heard this has not spoken since. The person may have moved, or the void may have shifted.",
  },
  {
    id: "s21",
    kind: "survivor",
    x: 1280,
    y: 180,
    title: "One elderly, hospital corridor",
    detail: "BEAR thermal through a cracked door. Path from the apron is blocked by a fallen slab.",
    confidence: 0.76,
    lastUpdateSec: MISSION_START_SEC - 40,
    sourceRobot: "bear",
    priority: 2,
    people: 1,
    access: "Hospital corridor. Needs a heavy or a new route around the slab.",
    status: "acknowledged",
  },
  {
    id: "h7",
    kind: "hazard",
    x: 860,
    y: 360,
    title: "Overpass pancake",
    detail: "Harbor Street overpass has come down. Aftershock risk on the north face. Do not send heavies under.",
    confidence: 0.9,
    lastUpdateSec: MISSION_START_SEC - 18,
    sourceRobot: "kite",
    status: "acknowledged",
  },
  {
    id: "h12",
    kind: "hazard",
    x: 640,
    y: 520,
    title: "Gas near market",
    detail: "LEL spike on THREAD. Wind is pushing toward School Lane. People in the school are still a maybe.",
    confidence: 0.71,
    lastUpdateSec: MISSION_START_SEC - 22,
    sourceRobot: "thread",
    status: "new",
  },
  {
    id: "b-harbor",
    kind: "blocked",
    x: 900,
    y: 400,
    title: "Harbor Street cut",
    detail: "Ground unit says the street is closed between 3rd and 4th. Aerial thinks a shoulder may have opened.",
    confidence: 0.6,
    lastUpdateSec: MISSION_START_SEC - 50,
    sourceRobot: "bear",
    status: "contested",
  },
  {
    id: "r-alley",
    kind: "route",
    x: 560,
    y: 300,
    title: "Service alley, Harbor A",
    detail: "KITE lidar sees a 1.4m gap behind Harbor House A. Possible THREAD path to the balcony voices.",
    confidence: 0.74,
    lastUpdateSec: MISSION_START_SEC - 12,
    sourceRobot: "kite",
    status: "new",
    access: "UAV-confirmed width. Ground not yet walked.",
  },
];

export const simEvents: SimEvent[] = [
  {
    at: 8,
    type: "route",
    discovery: {
      id: "r-culvert",
      kind: "route",
      x: 270,
      y: 300,
      title: "Culvert under the quay",
      detail: "KITE found an open culvert west of the parking structure. Tight. THREAD-class only. Could flank MOLE's last-known.",
      confidence: 0.63,
      lastUpdateSec: MISSION_START_SEC + 8,
      sourceRobot: "kite",
      status: "new",
      access: "Pipe / culvert. Snake only.",
    },
  },
  {
    at: 18,
    type: "confidence",
    discoveryId: "s14",
    confidence: 0.91,
    detail: "Child answered a second knock. Positions tightened to east rooms, 3rd floor.",
  },
  {
    at: 32,
    type: "comms",
    state: "degraded",
    lost: ["mole", "bear"],
    note: "Hospital wing is shadowing BEAR. MOLE still dark. Commands to either will queue on RELAY.",
  },
  {
    at: 45,
    type: "conflict",
    conflict: {
      id: "c-harbor",
      title: "Harbor Street disagrees",
      detail: "KITE's latest pass shows a 2m shoulder on the south curb. BEAR's last bumper camera, now stale, showed the same span blocked. Aerial is newer. Ground is closer.",
      x: 900,
      y: 400,
      aerial: "Shoulder looks open · 12s · KITE-2",
      ground: "Full block · 1m+ stale · BEAR-3",
    },
  },
  {
    at: 58,
    type: "survivor",
    discovery: {
      id: "s27",
      kind: "survivor",
      x: 300,
      y: 760,
      title: "Acoustic, school west wall",
      detail: "WHISPER sidelobe. One adult, intermittent. School is structurally green. Access is good if Harbor is not used.",
      confidence: 0.48,
      lastUpdateSec: MISSION_START_SEC + 58,
      sourceRobot: "whisper",
      priority: 3,
      people: 1,
      access: "School west wall. Ground floor inferred.",
      status: "new",
    },
  },
  {
    at: 72,
    type: "aftershock",
    note: "M4.1 aftershock. Facade risk on Harbor House B. Inferred tiles just became guesses again.",
  },
  {
    at: 78,
    type: "hazard",
    discovery: {
      id: "h-facade",
      kind: "hazard",
      x: 960,
      y: 150,
      title: "Harbor House B facade",
      detail: "Aftershock dropped cladding on the north face. Do not stage under. Inferred floorplan is now untrusted.",
      confidence: 0.8,
      lastUpdateSec: MISSION_START_SEC + 78,
      sourceRobot: "kite",
      status: "new",
    },
  },
  {
    at: 96,
    type: "restore",
    robotId: "mole",
    dump: "MOLE store-and-forward just hit RELAY. Tapping continues. Two distinct rhythms. Battery 38%. Still inside.",
  },
];

export const initialConflicts: Conflict[] = [];

export function mapKnownFrom(list: Building[]) {
  const weights = { confirmed: 1, inferred: 0.45, unknown: 0 };
  const total = list.reduce((a, b) => a + b.w * b.h, 0);
  const known = list.reduce((a, b) => a + b.w * b.h * weights[b.knowledge], 0);
  return known / total;
}
