import type { Building, Conflict, Discovery, Robot, SimEvent, Street } from "./types";

export const INCIDENT = {
  name: "Op Halcyon",
  place: "Halcyon Waterfront · Sector 4",
  magnitude: "6.8 Mw",
  startLabel: "05 Sep 2026 · 09:13 local",
  peopleMissing: 40,
  robotsDeployed: 6,
  mapKnownAtOpen: 0.39,
};

export const MISSION_START_SEC = 47 * 60;

export const buildings: Building[] = [
  { id: "b1", name: "Quay parking structure", x: 188, y: 128, w: 168, h: 148, kind: "parking", knowledge: "confirmed", damage: "collapsed" },
  { id: "b2", name: "Waterfront flats", x: 92, y: 132, w: 78, h: 142, kind: "housing", knowledge: "confirmed", damage: "intact" },
  { id: "b3", name: "Harbor House A", x: 378, y: 122, w: 108, h: 154, kind: "housing", knowledge: "confirmed", damage: "partial" },
  { id: "b4", name: "Harbor House B", x: 502, y: 128, w: 124, h: 148, kind: "housing", knowledge: "inferred", damage: "partial" },
  { id: "b5", name: "St. Mira Hospital", x: 692, y: 72, w: 176, h: 176, kind: "hospital", knowledge: "confirmed", damage: "partial" },
  { id: "b6", name: "Hospital annex", x: 708, y: 268, w: 118, h: 78, kind: "hospital", knowledge: "unknown", damage: "unknown" },
  { id: "b7", name: "North dark block", x: 828, y: 64, w: 132, h: 196, kind: "housing", knowledge: "unknown", damage: "unknown" },
  { id: "b8", name: "Canal civic hall", x: 188, y: 328, w: 128, h: 88, kind: "civic", knowledge: "inferred", damage: "intact" },
  { id: "b9", name: "Pump station", x: 92, y: 328, w: 72, h: 88, kind: "industrial", knowledge: "confirmed", damage: "intact" },
  { id: "b10", name: "Covered market", x: 348, y: 328, w: 168, h: 96, kind: "market", knowledge: "confirmed", damage: "partial" },
  { id: "b11", name: "Clinic 4", x: 538, y: 332, w: 96, h: 88, kind: "hospital", knowledge: "confirmed", damage: "intact" },
  { id: "b12", name: "Yard warehouses", x: 828, y: 388, w: 128, h: 148, kind: "industrial", knowledge: "unknown", damage: "unknown" },
  { id: "b13", name: "Sector 4 school", x: 148, y: 468, w: 168, h: 108, kind: "school", knowledge: "confirmed", damage: "intact" },
  { id: "b14", name: "South yards", x: 538, y: 468, w: 210, h: 108, kind: "industrial", knowledge: "inferred", damage: "partial" },
  { id: "b15", name: "Canal cottages", x: 348, y: 468, w: 168, h: 108, kind: "housing", knowledge: "confirmed", damage: "partial" },
];

export const streets: Street[] = [
  { id: "s1", name: "Canal Road", d: "M70 118 H960", knowledge: "confirmed" },
  { id: "s2", name: "Harbor Street", d: "M70 300 H960", knowledge: "confirmed", blocked: true },
  { id: "s3", name: "Market Row", d: "M70 442 H960", knowledge: "inferred" },
  { id: "s4", name: "School Lane", d: "M70 596 H700", knowledge: "confirmed" },
  { id: "s5", name: "1st Ave", d: "M168 60 V620", knowledge: "confirmed" },
  { id: "s6", name: "2nd Ave", d: "M332 60 V620", knowledge: "confirmed" },
  { id: "s7", name: "3rd Ave", d: "M492 60 V620", knowledge: "inferred" },
  { id: "s8", name: "4th Ave", d: "M652 60 V620", knowledge: "confirmed" },
  { id: "s9", name: "5th Ave", d: "M812 60 V420", knowledge: "unknown" },
];

export const initialRobots: Robot[] = [
  {
    id: "kite",
    callsign: "KITE-2",
    class: "uav",
    role: "rooftop mapping",
    x: 548,
    y: 214,
    heading: 28,
    battery: 64,
    lastHeardSec: MISSION_START_SEC - 3,
    radio: "strong",
    status: "mapping",
    payload: ["RGB", "lidar strip", "thermal"],
    can: ["map", "route-find", "overhead"],
    notes: "Flying a lawnmower over Harbor House. Best eyes we have. Cannot enter voids.",
  },
  {
    id: "mole",
    callsign: "MOLE-1",
    class: "crawler",
    role: "confined space",
    x: 262,
    y: 204,
    heading: 210,
    battery: 41,
    lastHeardSec: MISSION_START_SEC - 252,
    radio: "lost",
    status: "silent",
    payload: ["CO2", "cam", "mic"],
    can: ["void", "rubble"],
    notes: "Last packet from inside the parking pancake. Reported tapping, then nothing. May still be working. May be crushed. Treat as last-known.",
  },
  {
    id: "whisper",
    callsign: "WHISPER-4",
    class: "acoustic",
    role: "voice / knock listen",
    x: 428,
    y: 168,
    heading: 90,
    battery: 77,
    lastHeardSec: MISSION_START_SEC - 6,
    radio: "strong",
    status: "searching",
    payload: ["array mics", "knock"],
    can: ["listen", "localize"],
    notes: "Pinned on Harbor House A. Three voices, one small. Wants a snake or crawler to enter.",
  },
  {
    id: "bear",
    callsign: "BEAR-3",
    class: "heavy",
    role: "debris & corridor",
    x: 718,
    y: 292,
    heading: 0,
    battery: 58,
    lastHeardSec: MISSION_START_SEC - 9,
    radio: "weak",
    status: "searching",
    payload: ["arm", "cam", "gas"],
    can: ["push", "hospital", "block"],
    notes: "On the hospital apron. Radio is thinning behind the wing. Path into the ward is contested.",
  },
  {
    id: "thread",
    callsign: "THREAD-5",
    class: "snake",
    role: "void entry",
    x: 402,
    y: 372,
    heading: 320,
    battery: 71,
    lastHeardSec: MISSION_START_SEC - 4,
    radio: "strong",
    status: "searching",
    payload: ["cam", "led", "temp"],
    can: ["void", "floor", "pipe"],
    notes: "Clear of the market. Fastest body we have for a third-floor void if a route exists.",
  },
  {
    id: "relay",
    callsign: "RELAY-6",
    class: "relay",
    role: "mesh mule",
    x: 338,
    y: 268,
    heading: 300,
    battery: 82,
    lastHeardSec: MISSION_START_SEC - 2,
    radio: "strong",
    status: "relaying",
    payload: ["mesh", "store-forward"],
    can: ["restore", "queue"],
    notes: "Holding line-of-sight toward MOLE. One block west and we may hear the crawler again.",
  },
];

export const initialDiscoveries: Discovery[] = [
  {
    id: "s14",
    kind: "survivor",
    x: 424,
    y: 158,
    title: "Three voices, Harbor House A",
    detail: "Two adults, one child, east face, roughly 3rd floor. Thermal matches. They answered a knock.",
    confidence: 0.82,
    lastUpdateSec: MISSION_START_SEC - 6,
    sourceRobot: "whisper",
    priority: 1,
    people: 3,
    access: "Balcony / inferred alley behind A. Not a void.",
    status: "new",
  },
  {
    id: "s09",
    kind: "survivor",
    x: 254,
    y: 208,
    title: "Tapping in the parking void",
    detail: "MOLE-1 heard rhythmic tapping under the pancake, then dropped. This is a life signal with a four-minute silence after it.",
    confidence: 0.54,
    lastUpdateSec: MISSION_START_SEC - 252,
    sourceRobot: "mole",
    priority: 1,
    people: 1,
    access: "Void under collapsed parking. Confined-space only.",
    status: "new",
    staleWarning: "The robot that heard this has not spoken since. The person may have moved, or the void may have shifted.",
  },
  {
    id: "s21",
    kind: "survivor",
    x: 758,
    y: 148,
    title: "One elderly, hospital corridor",
    detail: "BEAR thermal through a cracked door. Path from the apron is blocked by a fallen slab.",
    confidence: 0.76,
    lastUpdateSec: MISSION_START_SEC - 40,
    sourceRobot: "bear",
    priority: 2,
    people: 1,
    access: "Hospital corridor. Needs a heavy or a new route around the slab.",
    status: "acknowledged",
  },
  {
    id: "h7",
    kind: "hazard",
    x: 470,
    y: 292,
    title: "Overpass pancake",
    detail: "Harbor Street overpass has come down. Aftershock risk on the north face. Do not send heavies under.",
    confidence: 0.9,
    lastUpdateSec: MISSION_START_SEC - 18,
    sourceRobot: "kite",
    status: "acknowledged",
  },
  {
    id: "h12",
    kind: "hazard",
    x: 392,
    y: 396,
    title: "Gas near market",
    detail: "LEL spike on THREAD. Wind is pushing toward School Lane. People in the school are still a maybe.",
    confidence: 0.71,
    lastUpdateSec: MISSION_START_SEC - 22,
    sourceRobot: "thread",
    status: "new",
  },
  {
    id: "b-harbor",
    kind: "blocked",
    x: 508,
    y: 300,
    title: "Harbor Street cut",
    detail: "Ground unit says the street is closed between 3rd and 4th. Aerial thinks a shoulder may have opened.",
    confidence: 0.6,
    lastUpdateSec: MISSION_START_SEC - 50,
    sourceRobot: "bear",
    status: "contested",
  },
  {
    id: "r-alley",
    kind: "route",
    x: 388,
    y: 248,
    title: "Service alley, Harbor A",
    detail: "KITE lidar sees a 1.4m gap behind Harbor House A. Possible THREAD path to the balcony voices.",
    confidence: 0.74,
    lastUpdateSec: MISSION_START_SEC - 12,
    sourceRobot: "kite",
    status: "new",
    access: "UAV-confirmed width. Ground not yet walked.",
  },
];

export const simEvents: SimEvent[] = [
  {
    at: 8,
    type: "route",
    discovery: {
      id: "r-culvert",
      kind: "route",
      x: 128,
      y: 250,
      title: "Culvert under the quay",
      detail: "KITE found an open culvert west of the parking structure. Tight. THREAD-class only. Could flank MOLE's last-known.",
      confidence: 0.63,
      lastUpdateSec: MISSION_START_SEC + 8,
      sourceRobot: "kite",
      status: "new",
      access: "Pipe / culvert. Snake only.",
    },
  },
  {
    at: 18,
    type: "confidence",
    discoveryId: "s14",
    confidence: 0.91,
    detail: "Child answered a second knock. Positions tightened to east rooms, 3rd floor.",
  },
  {
    at: 32,
    type: "comms",
    state: "degraded",
    lost: ["mole", "bear"],
    note: "Hospital wing is shadowing BEAR. MOLE still dark. Commands to either will queue on RELAY.",
  },
  {
    at: 45,
    type: "conflict",
    conflict: {
      id: "c-harbor",
      title: "Harbor Street disagrees",
      detail: "KITE's latest pass shows a 2m shoulder on the south curb. BEAR's last bumper camera, now stale, showed the same span blocked. Aerial is newer. Ground is closer.",
      x: 508,
      y: 300,
      aerial: "Shoulder looks open · 12s · KITE-2",
      ground: "Full block · 1m+ stale · BEAR-3",
    },
  },
  {
    at: 58,
    type: "survivor",
    discovery: {
      id: "s27",
      kind: "survivor",
      x: 214,
      y: 512,
      title: "Acoustic, school west wall",
      detail: "WHISPER sidelobe. One adult, intermittent. School is structurally green. Access is good if Harbor is not used.",
      confidence: 0.48,
      lastUpdateSec: MISSION_START_SEC + 58,
      sourceRobot: "whisper",
      priority: 3,
      people: 1,
      access: "School west wall. Ground floor inferred.",
      status: "new",
    },
  },
  {
    at: 72,
    type: "aftershock",
    note: "M4.1 aftershock. Facade risk on Harbor House B. Inferred tiles just became guesses again.",
  },
  {
    at: 78,
    type: "hazard",
    discovery: {
      id: "h-facade",
      kind: "hazard",
      x: 560,
      y: 140,
      title: "Harbor House B facade",
      detail: "Aftershock dropped cladding on the north face. Do not stage under. Inferred floorplan is now untrusted.",
      confidence: 0.8,
      lastUpdateSec: MISSION_START_SEC + 78,
      sourceRobot: "kite",
      status: "new",
    },
  },
  {
    at: 96,
    type: "restore",
    robotId: "mole",
    dump: "MOLE store-and-forward just hit RELAY. Tapping continues. Two distinct rhythms. Battery 38%. Still inside.",
  },
];

export const initialConflicts: Conflict[] = [];

export function mapKnownFrom(buildings: Building[]) {
  const weights = { confirmed: 1, inferred: 0.45, unknown: 0 };
  const total = buildings.reduce((a, b) => a + b.w * b.h, 0);
  const known = buildings.reduce((a, b) => a + b.w * b.h * weights[b.knowledge], 0);
  return known / total;
}
